import '../../detect/domain/detection.dart';

/// Represents a set of detections that describe the same semantic group.
class DetectionGroup {
  const DetectionGroup({
    required this.id,
    required this.rawLabel,
    required this.displayLabel,
    required this.detections,
  });

  /// Stable identifier that can be referenced by other widgets.
  final String id;

  /// Raw label generated by the detector. Useful for debugging.
  final String rawLabel;

  /// Human-friendly label suitable for chips and cards.
  final String displayLabel;

  /// Individual detections that compose this group.
  final List<Detection> detections;

  /// Number of detections represented by this group.
  int get count => detections.length;

  /// Average confidence score for the group (0.0 - 1.0).
  double get averageConfidence {
    if (detections.isEmpty) {
      return 0;
    }
    final total = detections.fold<double>(0, (sum, detection) => sum + detection.confidence);
    return total / detections.length;
  }

  /// Friendly label that includes the item count when greater than one.
  String get friendlyLabel {
    if (count <= 1) {
      return displayLabel;
    }
    return '$displayLabel ($count items)';
  }
}
