from __future__ import annotations

import os
from functools import lru_cache
from html import escape

from fastapi import APIRouter, HTTPException, Request, status
from fastapi.responses import HTMLResponse, RedirectResponse

from schemas.public_listing import PublicListingResponse
from services.session_store import CashToClearSessionStore

router = APIRouter(tags=['public'])


@lru_cache(maxsize=1)
def get_public_listing_service() -> CashToClearSessionStore:
    return CashToClearSessionStore()


@router.get('/listings', response_class=HTMLResponse)
def list_public_listings(request: Request) -> str:
    cards = []
    for listing in get_public_listing_service().list_recent_public_listings(limit=12):
        cards.append(
            f"""
            <a class="card" href="{escape(listing.public_url)}">
              <span class="eyebrow">Public listing</span>
              <strong>{escape(listing.title)}</strong>
              <span>${listing.price_usd:.2f} · {escape(listing.condition.title())}</span>
            </a>
            """.strip()
        )

    listing_cards = '\n'.join(cards) or """
      <div class="card empty">
        <span class="eyebrow">No listings yet</span>
        <strong>Create the first one from /app.</strong>
      </div>
    """.strip()

    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>DECLuTTER-AI Listings</title>
    <meta name="description" content="Recent standalone listing pages generated by DECLuTTER-AI." />
    <link rel="canonical" href="{escape(_external_path(request, '/listings'))}" />
    <style>
      body {{ margin:0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background:#f5f8ff; color:#10213f; }}
      main {{ max-width:1100px; margin:0 auto; padding:2rem 1rem 3rem; }}
      .eyebrow {{ color:#3157ff; font-weight:900; text-transform:uppercase; letter-spacing:.08em; font-size:.74rem; }}
      h1 {{ margin:.2rem 0 .4rem; font-size:clamp(2rem, 5vw, 4rem); letter-spacing:-.06em; }}
      .lede {{ color:#5f6f8d; max-width:60ch; line-height:1.6; }}
      .grid {{ display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:1rem; margin-top:1.2rem; }}
      .card {{ display:grid; gap:.35rem; background:white; border:1px solid #d7e0ef; border-radius:22px; padding:1rem; text-decoration:none; color:inherit; box-shadow:0 18px 50px rgba(16,33,63,.08); }}
      .card span {{ color:#5f6f8d; }}
      .empty {{ border-style:dashed; }}
      a.back {{ display:inline-flex; margin-top:1rem; color:#234bd7; font-weight:900; }}
      @media (max-width: 900px) {{ .grid {{ grid-template-columns:1fr; }} }}
    </style>
  </head>
  <body>
    <main>
      <p class="eyebrow">Standalone pages</p>
      <h1>Recent DECLuTTER-AI listings</h1>
      <p class="lede">These pages are the shareable output from the seller app and operator flow. Open one to see the current public result format.</p>
      <div class="grid">{listing_cards}</div>
      <a class="back" href="/">← Back to DECLuTTER-AI</a>
    </main>
  </body>
</html>"""


@router.get('/public/listings/{listing_id}/packet', response_model=PublicListingResponse)
@router.get('/listings/{listing_id}/packet', response_model=PublicListingResponse, include_in_schema=False)
def get_public_listing_packet(listing_id: str) -> PublicListingResponse:
    try:
        return get_public_listing_service().get_public_listing(listing_id)
    except KeyError as exc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(exc).strip("'"),
        ) from exc


@router.get('/public/listings/{listing_id}', include_in_schema=False)
def redirect_legacy_public_listing(listing_id: str) -> RedirectResponse:
    return RedirectResponse(url=f'/listings/{listing_id}', status_code=status.HTTP_307_TEMPORARY_REDIRECT)


@router.get('/listings/{listing_id}', response_class=HTMLResponse)
def get_public_listing(request: Request, listing_id: str) -> str:
    try:
        return get_public_listing_service().render_public_listing_html(
            listing_id,
            canonical_url=_external_path(request, f'/listings/{listing_id}'),
        )
    except KeyError as exc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(exc).strip("'"),
        ) from exc


def _external_path(request: Request, internal_path: str) -> str:
    configured_prefix = os.getenv('DECLUTTER_PUBLIC_BASE_PATH', '').strip('/')
    forwarded_prefix = request.headers.get('x-forwarded-prefix', '').strip('/')
    prefix = configured_prefix or forwarded_prefix
    path = internal_path if internal_path.startswith('/') else f'/{internal_path}'
    if prefix and not path.startswith(f'/{prefix}/'):
        path = f'/{prefix}{path}'

    proto = request.headers.get('x-forwarded-proto', request.url.scheme)
    host = request.headers.get('host', request.url.netloc)
    return f'{proto}://{host}{path}'
